const SAVE_ALL_ARTICLE = 'SAVE_ALL_ARTICLE';
const SAVE_AUDIO_LIST = 'SAVE_AUDIO_LIST';
const SAVE_ALL_BOOK = 'SAVE_ALL_BOOK';
const SAVE_CURRENT_BOOK = 'SAVE_CURRENT_BOOK';

export { SAVE_ALL_ARTICLE, SAVE_AUDIO_LIST, SAVE_ALL_BOOK, SAVE_CURRENT_BOOK };
